repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [ '--fix=lf' ]
      - id: end-of-file-fixer

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: migrations
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: migrations
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        exclude: migrations
