[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "asu"
version = "0.1.0"
dependencies = [
    "django ~= 4.2",
    "redis ~= 5.0",
    "hiredis ~= 2.2",
    "psycopg[c] ~= 3.1",
    "djangorestframework ~= 3.14",
    "drf-spectacular",
    "factory-boy ~= 3.3",
    "celery ~= 5.3",
    "django-celery-beat ~= 2.5",
    "drf-nested-routers ~= 0.93",
    "django-filter ~= 23.2",
    "channels[daphne] ~= 4.0",
    "channels-redis ~= 4.1",
    "asgiref ~= 3.7",
    "sorl-thumbnail ~= 12.10",
    "Pillow ~= 10.1",
    "python-magic ~= 0.4",
    "django-oauth-toolkit ~= 2.3",
    "django-two-factor-auth ~= 1.15",
    "phonenumbers ~= 8.13",
    "django-widget-tweaks ~= 1.5",
    "envanter ~= 1.2",
    "django-ipware ~= 5.0",
    "sentry-sdk ~= 1.34",
    "django-stubs-ext",
    "django-storages ~= 1.14",
    "boto3 ~= 1.28.84",
    "django-cors-headers ~= 4.3",
]

[project.optional-dependencies]
dev = [
    "django-debug-toolbar",
    "ipython",
    "coverage",
    "tblib",
    "watchfiles",
    "mypy",
    "django-stubs",
    "djangorestframework-stubs",
    "types-oauthlib",
    "types-Pillow",
    "celery-types",
]
prod = [
    "gunicorn ~= 21.2",
    "uvicorn ~= 0.24",
    "uvloop ~= 0.19",
    "httptools ~= 0.6",
    "websockets ~= 12.0",
]

[tool.black]
line-length = 88

[tool.ruff]
fix = true
fixable = ["I", "F401"]
show-fixes = true
select = [
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    "C", # flake8-comprehensions
    "B", # flake8-bugbear
    "RUF", # Ruff-specific
    "C4", # flake8-comprehensions
    "C90", # mccabe
    "I", # isort
]
target-version = "py311"
line-length = 88
exclude = ["migrations"]
ignore = ["B904", "RUF012"]

[tool.ruff.isort]
combine-as-imports = true
section-order = [
    "future",
    "standard-library",
    "django",
    "rest_framework",
    "third-party",
    "first-party",
    "local-folder",
]

[tool.ruff.isort.sections]
django = ["django"]
rest_framework = ["rest_framework"]

[tool.ruff.mccabe]
max-complexity = 20

[tool.mypy]
plugins = [
    "mypy_django_plugin.main",
    "mypy_drf_plugin.main",
]
strict = true
ignore_missing_imports = true
allow_subclassing_any = true

[tool.django-stubs]
django_settings_module = "asu.settings"

[tool.coverage.run]
source = ["asu"]
omit = [
    "asu/gateways/*"
]

[tool.coverage.report]
exclude_also = [
    "if TYPE_CHECKING:",
    'if settings.DEBUG',
    'if getattr\(self, "swagger_fake_view", False\):',
    'raise NotImplementedError',
    'raise AssertionError',
    'def __str__',
    'def __repr__',
]

[tool.coverage.html]
skip_empty = true
skip_covered = true
