[tool.black]
line-length = 79

[tool.isort]
profile = "black"
known_django = "django"
known_rest_framework = "rest_framework"
sections = "FUTURE,STDLIB,DJANGO,REST_FRAMEWORK,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
combine_as_imports=true
line_length = 79
