name: Measure coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build containers
      run: docker-compose -p zaida -f docker/docker-compose.yml up -d
    - name: Waiting a bit for the containers
      run: sleep 5s
      shell: bash
    - name: Run tests with coverage
      run: >-
          docker exec -t web /bin/sh -c
          "coverage run ./manage.py test --shuffle --settings=zaida.settings.test; coverage xml"

    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
