name: Run tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build containers
      run: docker-compose -p zeynep -f docker/docker-compose.yml up -d
    - name: Run tests
      run: docker exec -it web python manage.py test --settings=zeynep.settings.test --parallel 4 --shuffle --timing
